/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import '@stencil/core';




export namespace Components {

  interface BsAccordion {
    'className': string;
    'id': string;
    'items': string;
  }
  interface BsAccordionAttributes extends StencilHTMLAttributes {
    'className'?: string;
    'id'?: string;
    'items'?: string;
  }

  interface BsAlert {
    'className': string;
    'content': string;
    'header': string;
    'isDismissible': boolean;
    'type': number;
  }
  interface BsAlertAttributes extends StencilHTMLAttributes {
    'className'?: string;
    'content'?: string;
    'header'?: string;
    'isDismissible'?: boolean;
    'type'?: number;
  }

  interface BsBadge {
    'className': string;
    'content': string;
    'header': string;
    'href': string;
    'isPill': boolean;
    'type': number;
  }
  interface BsBadgeAttributes extends StencilHTMLAttributes {
    'className'?: string;
    'content'?: string;
    'header'?: string;
    'href'?: string;
    'isPill'?: boolean;
    'type'?: number;
  }

  interface BsBreadcrumb {
    'className': string;
    'items': string;
  }
  interface BsBreadcrumbAttributes extends StencilHTMLAttributes {
    'className'?: string;
    'items'?: string;
  }

  interface BsButton {
    'badgeType': number;
    'badgeValue': string;
    'className': string;
    'controls': Array<string>;
    'id': string;
    'isBlock': boolean;
    'isDisabled': boolean;
    'isExpanded': boolean;
    'isLarge': boolean;
    'isOutline': boolean;
    'isSmall': boolean;
    'target': string;
    'text': string;
    'toggle': string;
    'type': number;
  }
  interface BsButtonAttributes extends StencilHTMLAttributes {
    'badgeType'?: number;
    'badgeValue'?: string;
    'className'?: string;
    'controls'?: Array<string>;
    'id'?: string;
    'isBlock'?: boolean;
    'isDisabled'?: boolean;
    'isExpanded'?: boolean;
    'isLarge'?: boolean;
    'isOutline'?: boolean;
    'isSmall'?: boolean;
    'target'?: string;
    'text'?: string;
    'toggle'?: string;
    'type'?: number;
  }

  interface BsButtongroup {
    'buttonType': number;
    'buttons': string;
    'className': string;
    'id': string;
    'isLarge': boolean;
    'isSmall': boolean;
    'isVertical': boolean;
    'label': string;
  }
  interface BsButtongroupAttributes extends StencilHTMLAttributes {
    'buttonType'?: number;
    'buttons'?: string;
    'className'?: string;
    'id'?: string;
    'isLarge'?: boolean;
    'isSmall'?: boolean;
    'isVertical'?: boolean;
    'label'?: string;
  }

  interface BsCard {
    'body': string;
    'className': string;
    'footer': string;
    'header': string;
    'imgBottom': object;
    'imgTop': object;
  }
  interface BsCardAttributes extends StencilHTMLAttributes {
    'body'?: string;
    'className'?: string;
    'footer'?: string;
    'header'?: string;
    'imgBottom'?: object;
    'imgTop'?: object;
  }

  interface BsCardgroup {
    'cards': string;
    'className': string;
  }
  interface BsCardgroupAttributes extends StencilHTMLAttributes {
    'cards'?: string;
    'className'?: string;
  }

  interface BsCarousel {
    'className': string;
    'enableControls': boolean;
    'enableCrossfade': boolean;
    'enableIndicators': boolean;
    'id': string;
    'items': string;
    'options': string;
  }
  interface BsCarouselAttributes extends StencilHTMLAttributes {
    'className'?: string;
    'enableControls'?: boolean;
    'enableCrossfade'?: boolean;
    'enableIndicators'?: boolean;
    'id'?: string;
    'items'?: string;
    'options'?: string;
  }

  interface BsCollapse {
    'className': string;
    'content': string;
    'id': string;
    'isMulti': boolean;
    'options': string;
  }
  interface BsCollapseAttributes extends StencilHTMLAttributes {
    'className'?: string;
    'content'?: string;
    'id'?: string;
    'isMulti'?: boolean;
    'options'?: string;
  }

  interface BsDropdown {
    'className': string;
    'dropLeft': boolean;
    'dropRight': boolean;
    'dropUp': boolean;
    'formFl': boolean;
    'id': string;
    'isSplit': boolean;
    'items': string;
    'label': string;
    'menuOnly': boolean;
    'multi': boolean;
    'type': number;
    'value': string;
  }
  interface BsDropdownAttributes extends StencilHTMLAttributes {
    'className'?: string;
    'dropLeft'?: boolean;
    'dropRight'?: boolean;
    'dropUp'?: boolean;
    'formFl'?: boolean;
    'id'?: string;
    'isSplit'?: boolean;
    'items'?: string;
    'label'?: string;
    'menuOnly'?: boolean;
    'multi'?: boolean;
    'type'?: number;
    'value'?: string;
  }

  interface BsForm {
    'rows': string;
    'value': string;
  }
  interface BsFormAttributes extends StencilHTMLAttributes {
    'rows'?: string;
    'value'?: string;
  }

  interface BsInputgroup {
    'appendedLabel': string;
    'className': string;
    'description': string;
    'id': string;
    'isLarge': boolean;
    'isSmall': boolean;
    'label': string;
    'placeholder': string;
    'prependedLabel': string;
    'type': number;
    'value': string;
  }
  interface BsInputgroupAttributes extends StencilHTMLAttributes {
    'appendedLabel'?: string;
    'className'?: string;
    'description'?: string;
    'id'?: string;
    'isLarge'?: boolean;
    'isSmall'?: boolean;
    'label'?: string;
    'placeholder'?: string;
    'prependedLabel'?: string;
    'type'?: number;
    'value'?: string;
  }

  interface BsJumbotron {
    'className': string;
    'content': string;
    'isFluid': boolean;
    'lead': string;
  }
  interface BsJumbotronAttributes extends StencilHTMLAttributes {
    'className'?: string;
    'content'?: string;
    'isFluid'?: boolean;
    'lead'?: string;
  }

  interface BsListgroup {
    'className': string;
    'colWidth': number;
    'enableFade': boolean;
    'isFlush': boolean;
    'isTabs': boolean;
    'items': string;
  }
  interface BsListgroupAttributes extends StencilHTMLAttributes {
    'className'?: string;
    'colWidth'?: number;
    'enableFade'?: boolean;
    'isFlush'?: boolean;
    'isTabs'?: boolean;
    'items'?: string;
  }

  interface BsModal {
    'body': string;
    'button': string;
    'className': string;
    'disableFade': boolean;
    'footer': string;
    'hideCloseButton': boolean;
    'id': string;
    'isCentered': boolean;
    'isLarge': boolean;
    'isSmall': boolean;
    'onRenderBody': string;
    'onRenderFooter': string;
  }
  interface BsModalAttributes extends StencilHTMLAttributes {
    'body'?: string;
    'button'?: string;
    'className'?: string;
    'disableFade'?: boolean;
    'footer'?: string;
    'hideCloseButton'?: boolean;
    'id'?: string;
    'isCentered'?: boolean;
    'isLarge'?: boolean;
    'isSmall'?: boolean;
    'onRenderBody'?: string;
    'onRenderFooter'?: string;
  }

  interface BsNav {
    'className': string;
    'enableFade': boolean;
    'enableFill': boolean;
    'id': string;
    'isJustified': boolean;
    'isPills': boolean;
    'isTabs': boolean;
    'isVertical': boolean;
    'items': string;
  }
  interface BsNavAttributes extends StencilHTMLAttributes {
    'className'?: string;
    'enableFade'?: boolean;
    'enableFill'?: boolean;
    'id'?: string;
    'isJustified'?: boolean;
    'isPills'?: boolean;
    'isTabs'?: boolean;
    'isVertical'?: boolean;
    'items'?: string;
  }

  interface BsNavbar {
    'brand': string;
    'brandUrl': string;
    'className': string;
    'enableSearch': boolean;
    'id': string;
    'items': string;
    'searchBox': string;
    'type': number;
  }
  interface BsNavbarAttributes extends StencilHTMLAttributes {
    'brand'?: string;
    'brandUrl'?: string;
    'className'?: string;
    'enableSearch'?: boolean;
    'id'?: string;
    'items'?: string;
    'searchBox'?: string;
    'type'?: number;
  }

  interface BsPagination {
    'alignment': number;
    'className': string;
    'icon': string;
    'isLarge': boolean;
    'isSmall': boolean;
    'label': string;
    'numberOfPages': number;
  }
  interface BsPaginationAttributes extends StencilHTMLAttributes {
    'alignment'?: number;
    'className'?: string;
    'icon'?: string;
    'isLarge'?: boolean;
    'isSmall'?: boolean;
    'label'?: string;
    'numberOfPages'?: number;
  }

  interface BsPopover {
    'btnProps': string;
    'className': string;
    'isDismissible': boolean;
    'options': string;
    'type': number;
  }
  interface BsPopoverAttributes extends StencilHTMLAttributes {
    'btnProps'?: string;
    'className'?: string;
    'isDismissible'?: boolean;
    'options'?: string;
    'type'?: number;
  }

  interface BsProgress {
    'className': string;
    'isAnimated': boolean;
    'isStriped': boolean;
    'label': string;
    'max': number;
    'min': number;
    'size': number;
  }
  interface BsProgressAttributes extends StencilHTMLAttributes {
    'className'?: string;
    'isAnimated'?: boolean;
    'isStriped'?: boolean;
    'label'?: string;
    'max'?: number;
    'min'?: number;
    'size'?: number;
  }

  interface BsProgressgroup {
    'className': string;
    'isMultiple': boolean;
    'progressbars': string;
  }
  interface BsProgressgroupAttributes extends StencilHTMLAttributes {
    'className'?: string;
    'isMultiple'?: boolean;
    'progressbars'?: string;
  }

  interface BsTooltip {
    'btnProps': string;
    'className': string;
    'options': string;
    'type': number;
  }
  interface BsTooltipAttributes extends StencilHTMLAttributes {
    'btnProps'?: string;
    'className'?: string;
    'options'?: string;
    'type'?: number;
  }
}

declare global {
  interface StencilElementInterfaces {
    'BsAccordion': Components.BsAccordion;
    'BsAlert': Components.BsAlert;
    'BsBadge': Components.BsBadge;
    'BsBreadcrumb': Components.BsBreadcrumb;
    'BsButton': Components.BsButton;
    'BsButtongroup': Components.BsButtongroup;
    'BsCard': Components.BsCard;
    'BsCardgroup': Components.BsCardgroup;
    'BsCarousel': Components.BsCarousel;
    'BsCollapse': Components.BsCollapse;
    'BsDropdown': Components.BsDropdown;
    'BsForm': Components.BsForm;
    'BsInputgroup': Components.BsInputgroup;
    'BsJumbotron': Components.BsJumbotron;
    'BsListgroup': Components.BsListgroup;
    'BsModal': Components.BsModal;
    'BsNav': Components.BsNav;
    'BsNavbar': Components.BsNavbar;
    'BsPagination': Components.BsPagination;
    'BsPopover': Components.BsPopover;
    'BsProgress': Components.BsProgress;
    'BsProgressgroup': Components.BsProgressgroup;
    'BsTooltip': Components.BsTooltip;
  }

  interface StencilIntrinsicElements {
    'bs-accordion': Components.BsAccordionAttributes;
    'bs-alert': Components.BsAlertAttributes;
    'bs-badge': Components.BsBadgeAttributes;
    'bs-breadcrumb': Components.BsBreadcrumbAttributes;
    'bs-button': Components.BsButtonAttributes;
    'bs-buttonGroup': Components.BsButtongroupAttributes;
    'bs-card': Components.BsCardAttributes;
    'bs-cardGroup': Components.BsCardgroupAttributes;
    'bs-carousel': Components.BsCarouselAttributes;
    'bs-collapse': Components.BsCollapseAttributes;
    'bs-dropdown': Components.BsDropdownAttributes;
    'bs-form': Components.BsFormAttributes;
    'bs-inputGroup': Components.BsInputgroupAttributes;
    'bs-jumbotron': Components.BsJumbotronAttributes;
    'bs-listGroup': Components.BsListgroupAttributes;
    'bs-modal': Components.BsModalAttributes;
    'bs-nav': Components.BsNavAttributes;
    'bs-navbar': Components.BsNavbarAttributes;
    'bs-pagination': Components.BsPaginationAttributes;
    'bs-popover': Components.BsPopoverAttributes;
    'bs-progress': Components.BsProgressAttributes;
    'bs-progressGroup': Components.BsProgressgroupAttributes;
    'bs-tooltip': Components.BsTooltipAttributes;
  }


  interface HTMLBsAccordionElement extends Components.BsAccordion, HTMLStencilElement {}
  var HTMLBsAccordionElement: {
    prototype: HTMLBsAccordionElement;
    new (): HTMLBsAccordionElement;
  };

  interface HTMLBsAlertElement extends Components.BsAlert, HTMLStencilElement {}
  var HTMLBsAlertElement: {
    prototype: HTMLBsAlertElement;
    new (): HTMLBsAlertElement;
  };

  interface HTMLBsBadgeElement extends Components.BsBadge, HTMLStencilElement {}
  var HTMLBsBadgeElement: {
    prototype: HTMLBsBadgeElement;
    new (): HTMLBsBadgeElement;
  };

  interface HTMLBsBreadcrumbElement extends Components.BsBreadcrumb, HTMLStencilElement {}
  var HTMLBsBreadcrumbElement: {
    prototype: HTMLBsBreadcrumbElement;
    new (): HTMLBsBreadcrumbElement;
  };

  interface HTMLBsButtonElement extends Components.BsButton, HTMLStencilElement {}
  var HTMLBsButtonElement: {
    prototype: HTMLBsButtonElement;
    new (): HTMLBsButtonElement;
  };

  interface HTMLBsButtongroupElement extends Components.BsButtongroup, HTMLStencilElement {}
  var HTMLBsButtongroupElement: {
    prototype: HTMLBsButtongroupElement;
    new (): HTMLBsButtongroupElement;
  };

  interface HTMLBsCardElement extends Components.BsCard, HTMLStencilElement {}
  var HTMLBsCardElement: {
    prototype: HTMLBsCardElement;
    new (): HTMLBsCardElement;
  };

  interface HTMLBsCardgroupElement extends Components.BsCardgroup, HTMLStencilElement {}
  var HTMLBsCardgroupElement: {
    prototype: HTMLBsCardgroupElement;
    new (): HTMLBsCardgroupElement;
  };

  interface HTMLBsCarouselElement extends Components.BsCarousel, HTMLStencilElement {}
  var HTMLBsCarouselElement: {
    prototype: HTMLBsCarouselElement;
    new (): HTMLBsCarouselElement;
  };

  interface HTMLBsCollapseElement extends Components.BsCollapse, HTMLStencilElement {}
  var HTMLBsCollapseElement: {
    prototype: HTMLBsCollapseElement;
    new (): HTMLBsCollapseElement;
  };

  interface HTMLBsDropdownElement extends Components.BsDropdown, HTMLStencilElement {}
  var HTMLBsDropdownElement: {
    prototype: HTMLBsDropdownElement;
    new (): HTMLBsDropdownElement;
  };

  interface HTMLBsFormElement extends Components.BsForm, HTMLStencilElement {}
  var HTMLBsFormElement: {
    prototype: HTMLBsFormElement;
    new (): HTMLBsFormElement;
  };

  interface HTMLBsInputgroupElement extends Components.BsInputgroup, HTMLStencilElement {}
  var HTMLBsInputgroupElement: {
    prototype: HTMLBsInputgroupElement;
    new (): HTMLBsInputgroupElement;
  };

  interface HTMLBsJumbotronElement extends Components.BsJumbotron, HTMLStencilElement {}
  var HTMLBsJumbotronElement: {
    prototype: HTMLBsJumbotronElement;
    new (): HTMLBsJumbotronElement;
  };

  interface HTMLBsListgroupElement extends Components.BsListgroup, HTMLStencilElement {}
  var HTMLBsListgroupElement: {
    prototype: HTMLBsListgroupElement;
    new (): HTMLBsListgroupElement;
  };

  interface HTMLBsModalElement extends Components.BsModal, HTMLStencilElement {}
  var HTMLBsModalElement: {
    prototype: HTMLBsModalElement;
    new (): HTMLBsModalElement;
  };

  interface HTMLBsNavElement extends Components.BsNav, HTMLStencilElement {}
  var HTMLBsNavElement: {
    prototype: HTMLBsNavElement;
    new (): HTMLBsNavElement;
  };

  interface HTMLBsNavbarElement extends Components.BsNavbar, HTMLStencilElement {}
  var HTMLBsNavbarElement: {
    prototype: HTMLBsNavbarElement;
    new (): HTMLBsNavbarElement;
  };

  interface HTMLBsPaginationElement extends Components.BsPagination, HTMLStencilElement {}
  var HTMLBsPaginationElement: {
    prototype: HTMLBsPaginationElement;
    new (): HTMLBsPaginationElement;
  };

  interface HTMLBsPopoverElement extends Components.BsPopover, HTMLStencilElement {}
  var HTMLBsPopoverElement: {
    prototype: HTMLBsPopoverElement;
    new (): HTMLBsPopoverElement;
  };

  interface HTMLBsProgressElement extends Components.BsProgress, HTMLStencilElement {}
  var HTMLBsProgressElement: {
    prototype: HTMLBsProgressElement;
    new (): HTMLBsProgressElement;
  };

  interface HTMLBsProgressgroupElement extends Components.BsProgressgroup, HTMLStencilElement {}
  var HTMLBsProgressgroupElement: {
    prototype: HTMLBsProgressgroupElement;
    new (): HTMLBsProgressgroupElement;
  };

  interface HTMLBsTooltipElement extends Components.BsTooltip, HTMLStencilElement {}
  var HTMLBsTooltipElement: {
    prototype: HTMLBsTooltipElement;
    new (): HTMLBsTooltipElement;
  };

  interface HTMLElementTagNameMap {
    'bs-accordion': HTMLBsAccordionElement
    'bs-alert': HTMLBsAlertElement
    'bs-badge': HTMLBsBadgeElement
    'bs-breadcrumb': HTMLBsBreadcrumbElement
    'bs-button': HTMLBsButtonElement
    'bs-buttonGroup': HTMLBsButtongroupElement
    'bs-card': HTMLBsCardElement
    'bs-cardGroup': HTMLBsCardgroupElement
    'bs-carousel': HTMLBsCarouselElement
    'bs-collapse': HTMLBsCollapseElement
    'bs-dropdown': HTMLBsDropdownElement
    'bs-form': HTMLBsFormElement
    'bs-inputGroup': HTMLBsInputgroupElement
    'bs-jumbotron': HTMLBsJumbotronElement
    'bs-listGroup': HTMLBsListgroupElement
    'bs-modal': HTMLBsModalElement
    'bs-nav': HTMLBsNavElement
    'bs-navbar': HTMLBsNavbarElement
    'bs-pagination': HTMLBsPaginationElement
    'bs-popover': HTMLBsPopoverElement
    'bs-progress': HTMLBsProgressElement
    'bs-progressGroup': HTMLBsProgressgroupElement
    'bs-tooltip': HTMLBsTooltipElement
  }

  interface ElementTagNameMap {
    'bs-accordion': HTMLBsAccordionElement;
    'bs-alert': HTMLBsAlertElement;
    'bs-badge': HTMLBsBadgeElement;
    'bs-breadcrumb': HTMLBsBreadcrumbElement;
    'bs-button': HTMLBsButtonElement;
    'bs-buttonGroup': HTMLBsButtongroupElement;
    'bs-card': HTMLBsCardElement;
    'bs-cardGroup': HTMLBsCardgroupElement;
    'bs-carousel': HTMLBsCarouselElement;
    'bs-collapse': HTMLBsCollapseElement;
    'bs-dropdown': HTMLBsDropdownElement;
    'bs-form': HTMLBsFormElement;
    'bs-inputGroup': HTMLBsInputgroupElement;
    'bs-jumbotron': HTMLBsJumbotronElement;
    'bs-listGroup': HTMLBsListgroupElement;
    'bs-modal': HTMLBsModalElement;
    'bs-nav': HTMLBsNavElement;
    'bs-navbar': HTMLBsNavbarElement;
    'bs-pagination': HTMLBsPaginationElement;
    'bs-popover': HTMLBsPopoverElement;
    'bs-progress': HTMLBsProgressElement;
    'bs-progressGroup': HTMLBsProgressgroupElement;
    'bs-tooltip': HTMLBsTooltipElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
