/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
/* tslint:disable */

import '@stencil/core';




declare global {
  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}

  namespace StencilComponents {

    interface BsAlert {
      'className': string;
      'content': string;
      'header': string;
      'isDismissible': boolean;
      'type': number;
    }

    interface BsBadge {
      'className': string;
      'content': string;
      'header': string;
      'href': string;
      'isPill': boolean;
      'type': number;
    }

    interface BsBreadcrumb {
      'className': string;
      'items': string;
    }

    interface BsButton {
      'badgeType': number;
      'badgeValue': string;
      'className': string;
      'controls': Array<string>;
      'id': string;
      'isBlock': boolean;
      'isDisabled': boolean;
      'isExpanded': boolean;
      'isLarge': boolean;
      'isOutline': boolean;
      'isSmall': boolean;
      'target': string;
      'text': string;
      'toggle': string;
      'type': number;
    }

    interface BsButtongroup {
      'buttonType': number;
      'buttons': string;
      'className': string;
      'id': string;
      'isLarge': boolean;
      'isSmall': boolean;
      'isVertical': boolean;
      'label': string;
    }

    interface BsCard {
      'body': string;
      'className': string;
      'footer': string;
      'header': string;
      'imgBottom': object;
      'imgTop': object;
    }

    interface BsCardgroup {
      'cards': string;
      'className': string;
    }

    interface BsDropdown {
      'className': string;
      'formFl': boolean;
      'id': string;
      'items': string;
      'label': string;
      'multi': boolean;
      'type': number;
      'value': string;
    }

    interface BsForm {
      'rows': string;
      'value': string;
    }

    interface BsInputgroup {
      'appendedLabel': string;
      'className': string;
      'description': string;
      'id': string;
      'isLarge': boolean;
      'isSmall': boolean;
      'label': string;
      'placeholder': string;
      'prependedLabel': string;
      'type': number;
      'value': string;
    }

    interface BsModal {
      'body': string;
      'className': string;
      'disableFade': boolean;
      'footer': string;
      'hideCloseButton': boolean;
      'id': string;
      'isCentered': boolean;
      'isLarge': boolean;
      'isSmall': boolean;
      'title': string;
    }

    interface BsNavigation {
      'className': string;
      'enableFade': boolean;
      'enableFill': boolean;
      'id': string;
      'isJustified': string;
      'isPill': boolean;
      'isTabs': boolean;
      'isVertical': boolean;
      'items': string;
    }
  }


    interface HTMLBsAlertElement extends StencilComponents.BsAlert, HTMLStencilElement {}

    var HTMLBsAlertElement: {
      prototype: HTMLBsAlertElement;
      new (): HTMLBsAlertElement;
    };
    

    interface HTMLBsBadgeElement extends StencilComponents.BsBadge, HTMLStencilElement {}

    var HTMLBsBadgeElement: {
      prototype: HTMLBsBadgeElement;
      new (): HTMLBsBadgeElement;
    };
    

    interface HTMLBsBreadcrumbElement extends StencilComponents.BsBreadcrumb, HTMLStencilElement {}

    var HTMLBsBreadcrumbElement: {
      prototype: HTMLBsBreadcrumbElement;
      new (): HTMLBsBreadcrumbElement;
    };
    

    interface HTMLBsButtonElement extends StencilComponents.BsButton, HTMLStencilElement {}

    var HTMLBsButtonElement: {
      prototype: HTMLBsButtonElement;
      new (): HTMLBsButtonElement;
    };
    

    interface HTMLBsButtongroupElement extends StencilComponents.BsButtongroup, HTMLStencilElement {}

    var HTMLBsButtongroupElement: {
      prototype: HTMLBsButtongroupElement;
      new (): HTMLBsButtongroupElement;
    };
    

    interface HTMLBsCardElement extends StencilComponents.BsCard, HTMLStencilElement {}

    var HTMLBsCardElement: {
      prototype: HTMLBsCardElement;
      new (): HTMLBsCardElement;
    };
    

    interface HTMLBsCardgroupElement extends StencilComponents.BsCardgroup, HTMLStencilElement {}

    var HTMLBsCardgroupElement: {
      prototype: HTMLBsCardgroupElement;
      new (): HTMLBsCardgroupElement;
    };
    

    interface HTMLBsDropdownElement extends StencilComponents.BsDropdown, HTMLStencilElement {}

    var HTMLBsDropdownElement: {
      prototype: HTMLBsDropdownElement;
      new (): HTMLBsDropdownElement;
    };
    

    interface HTMLBsFormElement extends StencilComponents.BsForm, HTMLStencilElement {}

    var HTMLBsFormElement: {
      prototype: HTMLBsFormElement;
      new (): HTMLBsFormElement;
    };
    

    interface HTMLBsInputgroupElement extends StencilComponents.BsInputgroup, HTMLStencilElement {}

    var HTMLBsInputgroupElement: {
      prototype: HTMLBsInputgroupElement;
      new (): HTMLBsInputgroupElement;
    };
    

    interface HTMLBsModalElement extends StencilComponents.BsModal, HTMLStencilElement {}

    var HTMLBsModalElement: {
      prototype: HTMLBsModalElement;
      new (): HTMLBsModalElement;
    };
    

    interface HTMLBsNavigationElement extends StencilComponents.BsNavigation, HTMLStencilElement {}

    var HTMLBsNavigationElement: {
      prototype: HTMLBsNavigationElement;
      new (): HTMLBsNavigationElement;
    };
    

  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {
    'bs-alert': JSXElements.BsAlertAttributes;
    'bs-badge': JSXElements.BsBadgeAttributes;
    'bs-breadcrumb': JSXElements.BsBreadcrumbAttributes;
    'bs-button': JSXElements.BsButtonAttributes;
    'bs-buttonGroup': JSXElements.BsButtongroupAttributes;
    'bs-card': JSXElements.BsCardAttributes;
    'bs-cardGroup': JSXElements.BsCardgroupAttributes;
    'bs-dropdown': JSXElements.BsDropdownAttributes;
    'bs-form': JSXElements.BsFormAttributes;
    'bs-inputGroup': JSXElements.BsInputgroupAttributes;
    'bs-modal': JSXElements.BsModalAttributes;
    'bs-navigation': JSXElements.BsNavigationAttributes;
    }
  }

  namespace JSXElements {

    export interface BsAlertAttributes extends HTMLAttributes {
      'className'?: string;
      'content'?: string;
      'header'?: string;
      'isDismissible'?: boolean;
      'type'?: number;
    }

    export interface BsBadgeAttributes extends HTMLAttributes {
      'className'?: string;
      'content'?: string;
      'header'?: string;
      'href'?: string;
      'isPill'?: boolean;
      'type'?: number;
    }

    export interface BsBreadcrumbAttributes extends HTMLAttributes {
      'className'?: string;
      'items'?: string;
    }

    export interface BsButtonAttributes extends HTMLAttributes {
      'badgeType'?: number;
      'badgeValue'?: string;
      'className'?: string;
      'controls'?: Array<string>;
      'id'?: string;
      'isBlock'?: boolean;
      'isDisabled'?: boolean;
      'isExpanded'?: boolean;
      'isLarge'?: boolean;
      'isOutline'?: boolean;
      'isSmall'?: boolean;
      'target'?: string;
      'text'?: string;
      'toggle'?: string;
      'type'?: number;
    }

    export interface BsButtongroupAttributes extends HTMLAttributes {
      'buttonType'?: number;
      'buttons'?: string;
      'className'?: string;
      'id'?: string;
      'isLarge'?: boolean;
      'isSmall'?: boolean;
      'isVertical'?: boolean;
      'label'?: string;
    }

    export interface BsCardAttributes extends HTMLAttributes {
      'body'?: string;
      'className'?: string;
      'footer'?: string;
      'header'?: string;
      'imgBottom'?: object;
      'imgTop'?: object;
    }

    export interface BsCardgroupAttributes extends HTMLAttributes {
      'cards'?: string;
      'className'?: string;
    }

    export interface BsDropdownAttributes extends HTMLAttributes {
      'className'?: string;
      'formFl'?: boolean;
      'id'?: string;
      'items'?: string;
      'label'?: string;
      'multi'?: boolean;
      'type'?: number;
      'value'?: string;
    }

    export interface BsFormAttributes extends HTMLAttributes {
      'rows'?: string;
      'value'?: string;
    }

    export interface BsInputgroupAttributes extends HTMLAttributes {
      'appendedLabel'?: string;
      'className'?: string;
      'description'?: string;
      'id'?: string;
      'isLarge'?: boolean;
      'isSmall'?: boolean;
      'label'?: string;
      'placeholder'?: string;
      'prependedLabel'?: string;
      'type'?: number;
      'value'?: string;
    }

    export interface BsModalAttributes extends HTMLAttributes {
      'body'?: string;
      'className'?: string;
      'disableFade'?: boolean;
      'footer'?: string;
      'hideCloseButton'?: boolean;
      'id'?: string;
      'isCentered'?: boolean;
      'isLarge'?: boolean;
      'isSmall'?: boolean;
      'title'?: string;
    }

    export interface BsNavigationAttributes extends HTMLAttributes {
      'className'?: string;
      'enableFade'?: boolean;
      'enableFill'?: boolean;
      'id'?: string;
      'isJustified'?: string;
      'isPill'?: boolean;
      'isTabs'?: boolean;
      'isVertical'?: boolean;
      'items'?: string;
    }
  }

  interface HTMLElementTagNameMap {
    'bs-alert': HTMLBsAlertElement
    'bs-badge': HTMLBsBadgeElement
    'bs-breadcrumb': HTMLBsBreadcrumbElement
    'bs-button': HTMLBsButtonElement
    'bs-buttonGroup': HTMLBsButtongroupElement
    'bs-card': HTMLBsCardElement
    'bs-cardGroup': HTMLBsCardgroupElement
    'bs-dropdown': HTMLBsDropdownElement
    'bs-form': HTMLBsFormElement
    'bs-inputGroup': HTMLBsInputgroupElement
    'bs-modal': HTMLBsModalElement
    'bs-navigation': HTMLBsNavigationElement
  }

  interface ElementTagNameMap {
    'bs-alert': HTMLBsAlertElement;
    'bs-badge': HTMLBsBadgeElement;
    'bs-breadcrumb': HTMLBsBreadcrumbElement;
    'bs-button': HTMLBsButtonElement;
    'bs-buttonGroup': HTMLBsButtongroupElement;
    'bs-card': HTMLBsCardElement;
    'bs-cardGroup': HTMLBsCardgroupElement;
    'bs-dropdown': HTMLBsDropdownElement;
    'bs-form': HTMLBsFormElement;
    'bs-inputGroup': HTMLBsInputgroupElement;
    'bs-modal': HTMLBsModalElement;
    'bs-navigation': HTMLBsNavigationElement;
  }
}
declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;