/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
/* tslint:disable */

import '@stencil/core';




declare global {
  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}

  namespace StencilComponents {

    interface GdTextbox {
      'multi': boolean;
    }
  }


    interface HTMLGdTextboxElement extends StencilComponents.GdTextbox, HTMLStencilElement {}

    var HTMLGdTextboxElement: {
      prototype: HTMLGdTextboxElement;
      new (): HTMLGdTextboxElement;
    };
    

  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {
    'gd-textbox': JSXElements.GdTextboxAttributes;
    }
  }

  namespace JSXElements {

    export interface GdTextboxAttributes extends HTMLAttributes {
      'multi'?: boolean;
    }
  }

  interface HTMLElementTagNameMap {
    'gd-textbox': HTMLGdTextboxElement
  }

  interface ElementTagNameMap {
    'gd-textbox': HTMLGdTextboxElement;
  }
}
declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;